### ISSUE TITLE
black out on Unity 5.3.6

### ISSUE THREAD

**Issue by ootaken** [SiliconStudio/YEBIS-plugins#2]
-  Precondition

I installed YEBIS plugin accodring to the Apply YEBIS (https://github.com/SiliconStudio/YEBIS-plugins/blob/develop/Yebis4Unity.md).
- Procedure

If I check Yebis Post Effects (Script) on Test_Glare scene of Yebis assets, game image will be black out.
Other scene like blank project too.
- Environment

Unity 5.3.6 (64bits, https://unity3d.com/jp/unity/whats-new/unity-5.3.6)
Unity Editor 5.3.6 (64bits)
Unity Editor 5.3.6 (32bits)
Unity 5.3.0 (64bits)
Windows 10 Pro （Version 1607, OS Build 14393.51)
Processor Core i7 3667U 2.0GHz
Memory 8.00GB (7.82 avaliable)

**Comment by h-sao** [comment]
Thank you for your reporting.

Please you'll check that:
- "Graphics APIs for Windows" Setting - The first to use "OpenGL2"

![image](https://cloud.githubusercontent.com/assets/778582/17685194/ca803c2c-639c-11e6-86fb-ac65b8d46599.png)
- Main (Primary) Camera Setting - HDR

![image](https://cloud.githubusercontent.com/assets/778582/17685182/a660a020-639c-11e6-9b6a-1e179d1c58f8.png)

( Personally, I recommend using "Deferred" rendering path.)
- Currently, YEBIS for Unity (beta) supports on OpenGL2/3 on Android and iOS.  
  I mean, it works on mobile devices or Unity Preview window.  
  Doesn't work on Windows exe.

**Comment by ootaken** [comment]
Thank you for your configuration.

I could create Android apk that was Yebis enable with your configuration. Yebis for Unity works on Android.

But on preview, black out yet. I will check another configurations.

**Comment by ootaken** [comment]
As I research my GPU compatibility 

my chip : HD Graphics 4000 supports OpenGL 4.0

But OpenGL 4.0 doesn't not support full API of OpenGL 2.0

As I checked to build and run blank scene without YEBIS with Graphics APIs only with OpenGL2, black out occurred as same.

So, black out problem is because of my PC environments.

If team could, please improve error messages for this problem.

**Comment by h-sao** [comment]
Sorry for the beta version, it require the particular environment OpenGL2.
We have added the improvements about error log in the next release.
Thank you :)

**Comment by ootaken** [comment]
Thank you for your good support.

I will try on GPU supporting OpenGL2.x. Thank you.
